### ISSUE TITLE
Add comparison to @lukeed/uuid

### ISSUE THREAD

**Issue by eugene1g** [Brooooooklyn/uuid#18]
Hi,

It's great to see Node libraries push for better performance, especially with exciting new architectures like mixing Rust and JS implementations. 

Since the goal of this project is to maximize performance, it could be helpful to add benchmarking/comparison against https://github.com/lukeed/uuid which I think is the current lead for the fastest implementation of UUID.V4 for Node & browser. I did some benchmarks in my app and both libraries were neck-to-neck (specifically, using `@lukeed/uuid/secure`) so it might be a fair comparison.

**Comment by Brooooooklyn** [comment]
Closed in https://github.com/Brooooooklyn/uuid/commit/710d21bbf0dbfc568b8f388ee6fefcaf12803f0c
